#!/usr/bin/env python3
"""Create a local Herdr installation-review artifact without installing anything."""
import argparse
from datetime import datetime, timezone
from pathlib import Path
STATE_ROOT = Path.home() / ".local/state/agentswitchboard/android-herdr-migration"
TEXT = """# Herdr installation review\n\nStatus: PENDING — this file is a review artifact, not installation approval.\n\n## Source binding\n\n- Review timestamp (UTC):\n- Reviewer / actor:\n- Upstream repository: https://github.com/herdrdev/herdr\n- Official install documentation: https://herdr.dev/docs/install/\n- Exact release/tag/commit:\n- Source verification time:\n- Documented install method:\n- Candidate artifact URL or package identity:\n- Integrity mechanism / digest:\n- Upstream-supported platforms:\n- Explicit Android/Termux support claim: yes / no / not stated\n\n## Safety review\n\n- Linux aarch64 is not treated as Android compatibility proof: yes / no\n- `cargo install herdr` is documented by the pinned upstream source: yes / no\n- curl-pipe-shell is excluded as proof: yes / no\n- automatic Android `device_config` / battery mutation is excluded: yes / no\n- tmux remains installed and available for rollback: yes / no\n- uninstall / rollback procedure:\n- expected files and install scope:\n- network / subprocess / persistence implications reviewed:\n\n## Decision\n\n- Decision: APPROVED / REJECTED / BLOCKED / PENDING\n- Reason:\n- Exact installation command, only when APPROVED:\n- Exact rollback command, only when APPROVED:\n- Evidence artifact expected after installation:\n- Completion gate: rerun `bash Test-AgentSwitchboard-Android-Herdr.sh evidence` and require healthy binary identity before any server test.\n\n## Proof ceiling\n\nA completed review can approve one bounded installation method. It does not prove Android compatibility, server persistence, detach/reattach, agent-state detection, background survival, coding-agent behavior, or migration readiness.\n"""
def main() -> int:
    p=argparse.ArgumentParser(); p.add_argument("--write", action="store_true"); p.add_argument("--output", type=Path); a=p.parse_args()
    if not a.write and a.output is None: print(TEXT, end=""); return 0
    target=a.output.expanduser() if a.output else STATE_ROOT / f"herdr-install-review-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.md"; target.parent.mkdir(parents=True, exist_ok=True); target.write_text(TEXT, encoding="utf-8"); print(f"INSTALL_REVIEW={target}\nDECISION=PENDING\nNEXT_GATE=verify-current-official-upstream-source-and-complete-review"); return 0
if __name__ == "__main__": raise SystemExit(main())
